### ISSUE TITLE
Unable to locate element: [id="closeBtn"]

### ISSUE THREAD

**Issue by dejavoodooo** [ndepaola/mpc-autofill#13]
![image](https://user-images.githubusercontent.com/3332344/107679988-dfaa3200-6c62-11eb-8c39-308041759060.png)

**Comment by Zmk55** [comment]
Issue happens when you only upload 1 card on MPC because you can't order just a single card.

**Comment by ndepaola** [comment]
Should be fixed in the most recent update. Feel free to open another issue if it persists for you though!
