### ISSUE TITLE
Add a License 

### ISSUE THREAD

**Issue by LegNBass** [ndepaola/mpc-autofill#17]
I love what you're working on, and I'm a professional python dev that would like to make some contributions to help make improvements and add features. Without a license, I can't do any of that. 

Right now, this code is not open source and contributions (PRs) without written permission may be illegal in some countries. If you add a license, developers like myself could start contributing within the parameters of that license.

**Comment by ndepaola** [comment]
good call! i just added the GNU GPL license :)
