### ISSUE TITLE
fetches all cards that include card's name as a substring

### ISSUE THREAD

**Issue by agrasley** [ndepaola/mpc-autofill#2]
for some cards like, e.g., "Char," the site will fetch all cards that include the card's name as a substring. it would be nice in these cases to only get back variants of Char itself and not Esper Charm and Goblin Charbelcher.

**Comment by agrasley** [comment]
Thanks for this tool btw, it's great.

**Comment by ndepaola** [comment]
I'm working on this - will probably have to switch to postgres to implement it fully though!

**Comment by ndepaola** [comment]
Closing this now that I’ve implemented Elasticsearch-based search
