### ISSUE TITLE
Option to select original card design (if exists) for all entries at once and/or some nice filters.

### ISSUE THREAD

**Issue by nowak-ninja** [ndepaola/mpc-autofill#21]
Hey, thank You for such a great tool! I just finished selecting images for 800+ cards I would like to order and I have found that I am doing the repetitive thing of clicking every item and selecting an original design for 95% of the cards. These original images are usually last ones, but this is not a rule. Would be nice to have an option to mass select originals for all cards if they exist + little filter to include/exclude community designs, alternate versions, other languages (mostly Japanese), special edition and so on.

**Comment by Gikkman** [comment]
On the autofill front page, there is a button that says "Select Drives". Here, you can re-arrange the order in which the different drives appear. So click-and-drag the one's designs you want to the top (in this case, probably bearnt_toast). 

But if you also want to keep track of the exact printing version to get the first printing, that won't be possible. Card images are created by a huge community of different people, and everyone would have to adhere to some kind of standard to be able to chose print versions and that's likely never happening. So setting whos drive goes  first is t he best we'll probably ever going to have.

You can also click the little number under a card (that says like 2/10) to get a view of all available arts for a card. Makes if much smoother to pick the one you want.

**Comment by nowak-ninja** [comment]
Hey @Gikkman, thank You for the answer. I am already using "gallery view" to pick the design I want. I thought You have some kind of metadata for each image, hence my idea to put some filtering. Nevertheless, it's a great tool and a life changer!
