### ISSUE TITLE
Entering just a number in the search filed causes internal server error

### ISSUE THREAD

**Issue by Gikkman** [ndepaola/mpc-autofill#26]
The following entry in the search field on mpcautofill causes an internal server error:
```
1 Orgg
0
1 Orcish Lumberjack
```

It will cause an error for any "just a number" search actually.

**Comment by ndepaola** [comment]
Thanks for letting me know, I'll get onto fixing this when I can

**Comment by ndepaola** [comment]
Fixed in the latest release to production
