### ISSUE TITLE
Cannont sign in through Google

### ISSUE THREAD

**Issue by ikansai5** [ndepaola/mpc-autofill#3]
I've been trying to do the initial sign in step and each time I try to sign in I get this:

Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In.

There is no "Advanced" option to click and bypass this, like in the video.

**Comment by ikansai5** [comment]
I'm also using version 83.0.4103.106 for Chrome.

**Comment by ndepaola** [comment]
Thank you for letting me know about this! The Google Drive app for MPC Autofill's executable is currently unverified, so it seems like we've hit the cap of 100 users for unverified Drive apps already. (I didn't realise there was a cap on this until now) Currently rewriting the script to not require Google authentication which should hopefully resolve this issue for good.

**Comment by ndepaola** [comment]
Closing this issue as signing in with Google Drive is no longer required.
