### ISSUE TITLE
Cards not uploading

### ISSUE THREAD

**Issue by trigun0x2** [ndepaola/mpc-autofill#5]
Version 83.0.4103.106 (Official Build) (64-bit)

Properly download all card images but only uploads one image then stalls.

Not sure how to proceed.

**Comment by ndepaola** [comment]
Could you try downloading v1.2 and see how that goes for you?

**Comment by trigun0x2** [comment]
Awesome will try!

Just FYI, I got it to work by scrolling to the top mid-session. Eventually got stuck again later. Worked super well with a smaller set of cards though.

**Comment by trigun0x2** [comment]
Unrelated but the site seems to but and not generate the card back properly?
![image](https://user-images.githubusercontent.com/3936336/86400648-da611f80-bc5d-11ea-931c-d7ae83de058f.png)

**Comment by ndepaola** [comment]
Was the page still loading? I've never seen any issues with cardbacks not generating properly before, but if you've inputted a large order, it can take 30 seconds ish (depending on internet speed) to fetch card backs

**Comment by trigun0x2** [comment]
Page fully loaded and no error in console.
I ended up editing the `.xml` file manually and adding:
`<cardback>1LrVX0pUcye9n_0RtaDNVl2xPrQgn7CYf</cardback>`

**Comment by trigun0x2** [comment]
@ndepaola side note. For the http://mpcautofill.com/, is there a way to prioritize non-Scryfall and fallback on Scryfall images?

**Comment by ndepaola** [comment]
that’s the default behaviour of the site :) the next version of the site will come with more flexibility in ordering & selecting card sources as well, so keep an eye out for that in the next few weeks!

**Comment by trigun0x2** [comment]
> that’s the default behaviour of the site :) the next version of the site will come with more flexibility in ordering & selecting card sources as well, so keep an eye out for that in the next few weeks!

Awesome! Dream case, auto pick full art :P. I tend to click through half the cards for full art, then just give up lol.
