### ISSUE TITLE
Problems with CSV upload if you remove header row

### ISSUE THREAD

**Issue by Gikkman** [ndepaola/mpc-autofill#7]
I encountered an issue with the CSV upload functionality on the main site.

I tried uploading the following CSV file, and was met with a `500 Server Error` message
```
1,Plains,Island
1,Swamp,Mountain
```

I then tried a simpler version, which didn't give an error, but took me to the card selection page, with no cards loaded:
```
1,Plains,Island
```

Eventually, I realized I have to keep the header row in the CSV for the upload to work. I think it might be worth mentioning in the document, so other people don't do the same mistake. Or have a more informative error page, should you upload something incorrect.

---------------------
Steps to reproduce:

1. Download the csv template of the site
2. Open the csv file, and edit it to contain either of the examples above.
3. Save and close the csv file
4. Upload the csv file using the "Upload CSV" button

**Comment by ndepaola** [comment]
You're right that it's a bit unintuitive atm and a few other people have made the same mistake. When I have some free time I'll adjust the CSV handler code so it works properly if the first row isn't kept as the header row.

**Comment by ndepaola** [comment]
Fixed, closing this issue.
