### ISSUE TITLE
Automatic upload stall

### ISSUE THREAD

**Issue by Gikkman** [ndepaola/mpc-autofill#8]
Using the autofill program, it managed to download all the images but during upload, it only got to 17/489 (according to the cmd window, it had uploaded 18 to MPC), then it stopped. The `debug.log` file contained the following message:
```
[1129/233648.572:ERROR:directory_reader_win.cc(43)] FindFirstFile: The system cannot find the path specified. (0x3)
```

Here is a link with a pastebin of the entire cards.xml file
https://pastebin.com/8FtBk5V7

I had the autofill program in `T:\Photoshop\ORDER` (windows 10)

**Comment by ndepaola** [comment]
Hmm - can I confirm that you're running the release from a couple of days ago (v2.1)? Thanks for providing your xml - I'm testing your order on my machine (Windows 10 as well) and everything seems to be working properly (DL:144, UL: 27 so far) Do you have all 489 images in your `cards` directory?

**Comment by Gikkman** [comment]
After I re-ran the program a 3rd time it managed to finish just fine. Took little over 6h 40min. I don't even know if the message from `debug.log` I pasted matters. It seems to generate that message every time I run the autofill so maybe it is a remnant from something else.

Since the problem seems to be intermittent, my go-to guess is usually that it is network related. Especially since it seems the program doesn't do any concurrency

**Comment by ndepaola** [comment]
This problem should be fixed in the new release hopefully!
